name: AsciiDoc Build
on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docs
        working-directory: extension-definition-specifications
        run: |
          sudo apt-get install --fix-missing -y pandoc asciidoctor asciidoc-common wkhtmltopdf
          sh ../scripts/build_asciidoc.sh
      - uses: actions/upload-artifact@v3
        with:
          name: extensions
          path: temp/*

      - name: Setup Pages
        id: pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3

      - name: Upload Pages
        uses: actions/upload-pages-artifact@v2
        if: github.ref == 'refs/heads/main'
        with:
          path: '_site'

      - name: Deploy Pages
        id: deployment
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v2
