name: Process extensions into docbook, html, and docx formats
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build docs
        working-directory: extension-definition-specifications
        run: |
          sudo apt-get install -y pandoc asciidoctor asciidoc-common wkhtmltopdf
          sh ../scripts/build_asciidoc.sh
      - uses: actions/upload-artifact@v3
        with:
          name: extensions
          path: temp/*